### ISSUE TITLE
Update Project Plan 

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#359]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:
Update project plan with budget drawdown as well as IT resource requirements and HR working group requirements and Communication session with Divisional managers, HR working group, Payroll and employees.

#Outcome:
- [ ]  01ProjectMgmt/Rizing-SOW...-Tab - Timeline and Resources SOW V1.1 for full schedule
- [ ]  01ProjectMgmt/Rizing-SOW...-Tab - SAP Functional for @ivydavid 
- [ ]  01ProjectMgmt/Rizing-SOW...-Tab - Payroll

#To Complete this ticket:
- [ ]  
- [ ] 
- [ ]
