### ISSUE TITLE
Review Project Plan & RACI

### ISSUE THREAD

**Issue by lortrent** [lortrent/projects#372]
#Privacy of Information and Protection:
**Your opinion is your personal information. Please do not include any information which identifies you or others in your response.**

#Description:
Review the tabs for clarity.  DO not make any updates in these files.  Please let me know any issues.

#Outcome:
- [ ] 01ProjectMgmt/Rizing-SOW...-Tab - Timeline and Resources SOW V1.1 for full schedule
- [ ] 01ProjectMgmt/Rizing-SOW...-Tab - SAP Functional for @ivydavid
- [ ] 01ProjectMgmt/Rizing-SOW...-Tab - Payroll
- [ ]  01ProjectMgmt/Updated-RACI

#To Complete this ticket:
- [ ]  @dcairdcon has reviewed and emailed comments to LT
- [x]  @cegede has reviewed
- [ ]
